# Welcome to Jekyll!
#

# Site settings
title: Fusion Salon
owner: Fusion Salon # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
collections:
  profiles:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "stylists"
    values:
      layout: "stylist"

# Build settings
markdown: kramdown
#sass:
#  style: compressed
